# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Bite About It' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bite About It
  pod 'KeychainAccess'
  pod 'SwiftyJSON'
  pod 'Sourcery'

  target 'Bite About ItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bite About ItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
